/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: EthanFromEngland (https://sketchfab.com/EthanfromEngland)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/adventurer-character-stylised-figurine-meshy-90dc24a7e3d844aeb3947c158017420f
Title: Adventurer Character - Stylised Figurine [MESHY]
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0_Material_0_0: THREE.Mesh;
  };
  materials: {
    Material_0: THREE.MeshPhysicalMaterial;
  };
};

export function Experience(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/adventurer_character_-_stylised_figurine_meshy.glb",
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="STYLIZED_ADVENTURER_F_0922184115_refinefbx" scale={0.01}>
        <mesh
          name="Mesh_0_Material_0_0"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_0_Material_0_0.geometry}
          material={materials.Material_0}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/adventurer_character_-_stylised_figurine_meshy.glb");
